import React, { useEffect } from "react";
import { EventContext } from "../contexts/EventContext";
import { useContext } from "react";
import Head from "next/head";
import Image from "next/image";
import Calendar from "../components/Calendar";
import styles from "../styles/Home.module.css";
import useSWR from "swr";
import axios from "axios";
import EventCard from "../components/EventCard";

const fetcher = (url) => axios.get(url).then((res) => res.data);

export default function Home() {
  // see if possible to save events in context
  const { events, saveEvents } = useContext(EventContext);
  const { data, error } = useSWR("/api/events", fetcher);

  if (error) return "An error has occurred.";
  if (!data) return "Loading...";
  console.log(error);
  console.log(events);

  saveEvents(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-neutral-800 min-h-[100vh]">
        <div className="relative w-full h-full">
          <div className="absolute bg-neutral-800 bg-opacity-50 w-full h-full flex justify-center items-center text-violet-300 text-[60px] font-steelfish text-center">
            <h1>
              NATTKLUBBEN
              <br />
              NÄRA
              <br />
              STUDENTERNA
            </h1>
          </div>
          <video src="/mobile-hero.mp4" playsInline autoPlay loop muted />
        </div>
        <div className="pt-10">
          <h2 className="font-steelfish text-[100px] text-[#d57187] pl-4 pb-4">
            Schema <p className="inline text-5xl pl-6">🥳</p>
          </h2>

          <Calendar />
        </div>
        <div className="pt-10" onClick={() => console.log(events)}>
          <h2 className="font-steelfish text-[100px] text-[#d57187] pl-4 pb-4">
            Biljetter <p className="inline text-5xl pl-6">🎟️</p>
          </h2>
          <div className={styles.mediaScroller}>
            {data.map((event) => (
              <EventCard key={event.eventId} id={event.eventId} event={event} />
            ))}
          </div>
        </div>
      </main>
    </div>
  );
}
