import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-neutral-800 min-h-[100vh]">
        <div className="relative w-full h-full">
          <div className="absolute bg-neutral-800 bg-opacity-50 w-full h-full flex justify-center items-center text-violet-300 text-[40px] font-appareo text-center">
            <h1>
              Nattklubben
              <br />
              nära
              <br />
              studenterna
            </h1>
          </div>
          <video src="/mobile-hero.mp4" playsInline autoPlay loop muted />
        </div>
      </main>
    </div>
  );
}
